cs_courses = {
   110: "Essentials of Computer Science",
   112: "Introduction to Computer Programming", 
   108: "Intro to Computer Programming, Part A",
   109: "Intro to Computer Programming, Part B", 
   211: "Object Oriented Programming",
   262: "Introduction to Low-Level Programming", 
   306: "Synthesis of Ethics and Law for the Computing Professional",
   310: "Data Structures",
   321: "Software Engineering",
   330: "Formal Methods and Models",
   367: "Computer Systems and Programming",
   471: "Operating Systems",
   483: "Analysis of Algorithms",

   425: "Game Programming 1", 
   440: "Language Processors and Programming Environments",
   450: "Database Concepts",
   451: "Computer Graphics", 
   455: "Computer Communications and Networking",
   463: "Comparative Programming Languages",
   465: "Computer Systems Architecture",
   468: "Secure Programming and Systems",
   469: "Security Engineering", 
   475: "Concurrent and Distributed Systems",
   477: "Mobile Application Development", 
   480: "Introduction to Artificial Intelligence",
   482: "Computer Vision", 
   484: "Data Mining",
   485: "Autonomous Robotics",
   487: "Introduction to Cryptography",
   490: "Design Exhibition",
   491: "Industry-Sponsored Senior Design Project",
   499: "Special Topics in Computer Science"
}